conf/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
# IMG Mine!
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# Images, MINE! :
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import *

app_name = 'pages'
urlpatterns = [
    # Post
    path("", PostListView.as_view(), name="all"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    # Tags:
    path('tag/<slug:tg_slug>/', TagList.as_view(), name='tag_list'),
    # Comments:
    path('post/<int:pk>/comment', CommentCreateView.as_view(), name='post_comment_create'),
    path('post/<int:pk>/delete_comment', CommentDeleteView.as_view(success_url=reverse_lazy('post:all')),
         name='post_comment_delete'),
    # Likes:
    path('post/<int:pk>/like', AddLikeView.as_view(), name='post_like'),
    path('post/<int:pk>/dislike', DeleteLikeView.as_view(), name='post_dislike'),
]

pages/models.py
from django.conf import settings
from django.core.validators import MinLengthValidator
from django.db import models
# Taggit
from taggit.managers import TaggableManager  # Tags
# TinyMCE
from tinymce import models as tinymce_models


# Create your models here.

class Post(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    body = tinymce_models.HTMLField()
    image = models.ImageField(
        upload_to='img/%Y/%m/%d/',
        blank=True,
    )
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    tags = TaggableManager(blank=True)

    comments = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                      through='Comment', related_name='post_comments')

    # Favorites:
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                       through='Like', related_name='liked_posts')

    # Methods:
    def __str__(self):
        return self.title + " - " + self.created_at.strftime("%m/%d/%Y, %H:%M")


class Comment(models.Model):
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15: return self.text
        return self.text[:11] + ' ...'


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/3.0/ref/models/options/#unique-together
    class Meta:
        unique_together = ('post', 'user')

    def __str__(self):
        return f'{self.user.username} likes {self.post.title[:10]}'

pages/forms.py
from django import forms


# strip means to remove whitespace from the beginning and the end before storing the column
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

pages/views.py
# Django:
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.utils import IntegrityError
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
# Likes:
from django.views.decorators.csrf import csrf_exempt
# Views:
from django.views.generic import View, ListView, DetailView

# Forms:
from .forms import CommentForm
# Models:
from .models import Post, Comment, Like
from .owner import OwnerCreateView, OwnerDeleteView, OwnerUpdateView


# Post's views:

class PostListView(ListView):
    def get_queryset(self):
        post_list = Post.objects.order_by('-updated_at')[:10]
        return post_list


# ! DO IT!
class PostListViewPlusLike(ListView):
    model = Post

    def get(self, request):
        post_list = Post.objects.order_by('-updated_at')[:10]
        likes = []
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.liked_posts.values('id')
            # likes = [2, 4, ...] using list comprehension
            likes = [row['id'] for row in rows]
        ctx = {'post_list': thing_list, 'likes': likes}
        return render(request, self.template_name, ctx)


class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        comments = Comment.objects.filter(post=self.object).order_by('-updated_at')
        comment_form = CommentForm()
        context['comments'] = comments
        context['comment_form'] = comment_form

        # Likes:
        if self.request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = self.request.user.liked_posts.values('id')
            # likes = [2, 4, ...] using list comprehension
            likes = [row['id'] for row in rows]
            context['likes'] = likes

        return context


class PostCreateView(OwnerCreateView):
    model = Post
    fields = ['title', 'body', 'image', 'tags', ]
    success_url = reverse_lazy('pages:all')


class PostDeleteView(OwnerDeleteView):
    model = Post
    success_url = reverse_lazy('pages:all')


class PostUpdateView(OwnerUpdateView):
    model = Post
    fields = ['title', 'body', 'image', 'tags', ]
    success_url = reverse_lazy('pages:all')


# Tag's views

class TagList(ListView):
    model = Post
    template_name = 'pages/tag_list.html'

    def get_context_data(self, *args, **kwargs):
        print(self.kwargs, self.args)
        context = super().get_context_data()
        Post_list = Post.objects.filter(tags__slug=self.kwargs['tg_slug'])
        context['post_list'] = Post_list
        return context


# Comment's views:

class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk):
        f = get_object_or_404(Post, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, post=f)
        comment.save()
        return redirect(reverse('pages:post_detail', args=[pk]))


class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "pages/comment_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        post = self.object.post
        return reverse('pages:post_detail', args=[post.id])


# Like's views:

@method_decorator(csrf_exempt, name='dispatch')
class AddLikeView(LoginRequiredMixin, View):
    def post(self, request, pk):
        a = get_object_or_404(Post, id=pk)
        like_inst = Like(user=request.user, post=a)
        try:
            like_inst.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()


@method_decorator(csrf_exempt, name='dispatch')
class DeleteLikeView(LoginRequiredMixin, View):
    def post(self, request, pk):
        t = get_object_or_404(Post, id=pk)
        try:
            like_inst = Like.objects.get(user=request.user, post=t).delete()
        except Like.DoesNotExist as e:
            pass

        return HttpResponse()

templates/base/base_bootstrap.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
        crossorigin="anonymous"/>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <link rel="stylesheet" href="{% block css %} {% endblock %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"
          defer></script>
  <title>Django Blog</title>
  {% block style %} {% endblock %}
</head>
<body>
{% include "base/navbar.html" %}
{% block content %}
{% endblock %}
{% include "base/footer.html" %}
</body>
</html>

templates/base/footer.html
<!-- ! https://dev.to/robotspacefish/how-to-make-your-footer-stick-to-the-bottom-of-the-page-1im2 -->

<footer class="bd-footer p-3 p-md-5 mt-5 bg-light text-center text-sm-start">
  <div class="container">
    <ul class="bd-footer-links ps-0 mb-3">
      <li class="d-inline-block"><a href="https://github.com/twbs">GitHub</a></li>
      <li class="d-inline-block ms-3"><a href="https://twitter.com/getbootstrap">Twitter</a></li>
      <li class="d-inline-block ms-3"><a href="/docs/5.0/examples/">Examples</a></li>
      <li class="d-inline-block ms-3"><a href="/docs/5.0/about/overview/">About</a></li>
    </ul>
    <p class="mb-0">Designed and built with all the love in the world by the <a href="/docs/5.0/about/team/">Bootstrap
      team</a> with the help of <a href="https://github.com/twbs/bootstrap/graphs/contributors">our contributors</a>.
    </p>
    <p class="mb-0">Currently v5.0.0-beta3. Code licensed <a href="https://github.com/twbs/bootstrap/blob/main/LICENSE"
                                                             target="_blank" rel="license noopener">MIT</a>, docs <a
            href="https://creativecommons.org/licenses/by/3.0/" target="_blank" rel="license noopener">CC BY 3.0</a>.
    </p>
  </div>
</footer>

templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
  <div class="container">
    <a class="navbar-brand" href="{% url 'pages:all' %}">Blog</a>
    <button class="btn btn-outline-dark navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <!-- <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-light" type="submit">Search</button>
        </form> -->
      <div class="">
        {% if user.is_authenticated %}
          <div class="user__dropdown dropdown me-4">
            <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button"
               data-bs-toggle="dropdown" aria-expanded="false"> Dropdown </a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'pages:post_create' %}">Create new post</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li>
                <hr class="dropdown-divider"/>
              </li>
              <li><a class="dropdown-item" href="{% url 'logout' %}?next={% url 'pages:all' %}">Log out</a></li>
            </ul>
          </div>
        {% else %}
          <a href="{% url 'login' %}?next={% url 'pages:all' %}">
            <button type="button" class="btn btn-outline-light me-4">Log in</button>
          </a>

        {% endif %}
      </div>
      <div>
        <a href=""><i class="fas fa-search text-light"></i></a>
      </div>
    </div>
  </div>
</nav>

templates/pages/comment_delete.html
{% extends "base/base_bootstrap.html" %} {% block content %}
  <main class="container">
    <h1>Delete Comment</h1>

    <p>Are you sure you want to delete</p>
    <p>{{ comment.text }}?</p>

    <form action="" method="POST">
      {% csrf_token %}
      <input type="submit" class="btn btn-primary" value="Yes, delete."/>
      <a
              href="{% url 'pages:post_detail' comment.post.id %}"
              class="btn btn-secondary"
      >Cancel</a
      >
    </form>
  </main>
{% endblock %}

templates/pages/post_confirm_delete.html
{% extends "base/base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <main class="container">
    <h1>Delete post?</h1>

    <p>Are you sure you want to delete the post: "{{ post.title }}" ?</p>

    <form action="" method="POST">

      {% csrf_token %}
      <input type="submit" class="btn btn-dark" value="Yes, delete.">
    </form>
  </main>
{% endblock %}

templates/pages/post_detail.html
{% extends "base/base_bootstrap.html" %}

{% block content %}
  <main class="container" style="max-width: 75ch;">
    <h1 class="text-center my-5">
      {% if post.owner == user %}
        <span style="float: right;">
            <a class="text-dark mr-5" href="{% url 'pages:post_update' post.id %}"><i class="fas fa-pencil-alt"></i></a>
            <a class="text-dark" href="{% url 'pages:post_delete' post.id %}"><i class="far fa-trash-alt"></i></a>
            </span>
      {% endif %}
      {{ post.title }}
    </h1>
    <div>{{ post.body| safe }}</div>

    {% if post.image %}
      <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel" style="width: 100%;">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{{ post.image.url }}" class="d-block" alt="...">
          </div>
        </div>
      </div>
      <div class="alert alert-dark tags my-4 " role="alert">
        Tags: {% for tag in post.tags.all %} <a href="{% url 'pages:tag_list' tag.slug %}">#{{ tag }}</a> {% endfor %}
      </div>
    {% endif %}

    <div class="comment-section border-top pt-4">
      {% for comment in comments %}
        <div class="mb-2">
          <p class="fw-bold mb-0">{{ comment.owner }}:</p>
          <p class="mb-0">
            {{ comment.text }}
            {% if user == comment.owner %}
              <small class="mt-0 ms-2"><a href="{% url 'pages:post_comment_delete' comment.id %}"><i
                      class="fa fa-trash text-dark"></i></a></small>
            {% endif %}
          </p>
        </div>
      {% endfor %}
    </div>

    {% if user.is_authenticated %}
      <p>
        {% load crispy_forms_tags %}
      <form method="post" action="{% url 'pages:post_comment_create' post.id %}">
        {% csrf_token %}
        {{ comment_form|crispy }}
        <input class="mt-4 me-2 btn btn-dark" type="submit" value="Submit" id="submit_btn">


        <!-- Like buttons -->

        <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
        <a href="#submit_btn" onclick=
                "favPost('{% url 'pages:post_dislike' post.id %}', {{ post.id }} );return true;"
                {% if post.id not in likes %} style="display: none;" {% endif %}
           id="favorite_star_{{ post.id }}"
           class="btn btn-dark mt-4 me-2"
        >
          Dislike
        </a>
        <!-- the second href -->
        <a href="#submit_btn" onclick=
                "favPost('{% url 'pages:post_like' post.id %}', {{ post.id }} );return true;"
                {% if post.id in likes %} style="display: none;" {% endif %}
           id="unfavorite_star_{{ post.id }}"
           class="btn btn-dark mt-4 me-2"
        >
          Like
        </a>

        <!-- End of like buttons -->

      </form>
      </p>
    {% endif %}

  </main>
  <script
          src="https://code.jquery.com/jquery-3.6.0.min.js"
          integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
          crossorigin="anonymous"></script>

  <script>
    function favPost(url, thing_id) {
      console.log('Requesting JSON');
      $.post(url, {}, function (rowz) {
        console.log(url, 'finished');
        $("#unfavorite_star_" + thing_id).toggle();
        $("#favorite_star_" + thing_id).toggle();
      }).fail(function (xhr) {
        alert('Url failed with ' + xhr.status + ' ' + url);
      });
    }
  </script>


{% endblock content %}

templates/pages/post_form.html
{% extends "base/base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <main class="container">
    <p>
    <form action="" method="post" id="ad_form" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.media }}
      {{ form|crispy }}
      <input type="submit" class="btn btn-dark mt-4" value="Submit">
      <input type="submit" class="btn btn-dark mt-4 ml-" value="Cancel"
             onclick="window.location.href='{% url 'pages:all' %}';return false;">
    </form>
    </p>
  </main>
  <script>
    $("#ad_form").submit(function () {
      console.log('Checking file size');
      if (window.File && window.FileReader && window.FileList && window.Blob) {
        var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
        if (file && file.size > {{ form.max_upload_limit }}) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
          return false;
        }
      }
    });
  </script>
{% endblock %}

templates/pages/post_list.html
{% extends "base/base_bootstrap.html" %} {% load humanize %} {% load static %}
<!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block content %}

  <div
          class="d-flex justify-content-center align-items-center"
          style="width: 100vw; height: 25vh"
  >
    <h1>The blog</h1>
  </div>

  <main class="container">
    <div class="row mb-4">
      {% for post in post_list %} {% if forloop.counter == 1 %}
        <a href="{% url 'pages:post_detail' pk=post.id %}" class="bo">
          <div class="card text-dark bg-light mb-5">
            <div class="" style="overflow: auto">
              {% if post.image %}
                <div
                        class="img_div_first"
                        style="background-image: url('{{ post.image.url }}');"
                ></div>
              {% else %}
                <div class="img_div"></div>
              {% endif %}
            </div>
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">...</p>
              <p class="card-text">
                <small class="text-muted">Last updated 3 mins ago</small>
              </p>
            </div>
          </div>
        </a>

      {% else %}
        <div class="col-xl-4 col-lg-6 col-md-12 mb-4">
          <a href="{% url 'pages:post_detail' post.id %}" class="bo">
            <div class="card text-dark bg-light">
              <div class="row g-0">
                <div class="col-md-4" style="overflow: auto">
                  {% if post.image %}
                    <div
                            class="img_div"
                            style="background-image: url('{{ post.image.url }}');"
                    ></div>
                  {% else %}
                    <div class="img_div"></div>
                  {% endif %}
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">...</p>
                    <p class="card-text">
                      <small class="text-muted"
                      >Last update: {{ post.updated_at | naturaltime }}</small
                      >
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </a>
        </div>
      {% endif %} {% endfor %}
    </div>
  </main>

{% endblock content %}

templates/pages/tag_list.html
{% extends "base/base_bootstrap.html" %}

{% block content %}

  <div class="d-flex justify-content-center align-items-center" style="width: 100vw; height: 25vh;">
    <h1>The blog</h1>
  </div>

  <main class="container">
    <div class="row mb-4">
      {% for post in post_list %}

        <div class="col-xl-4 col-lg-6 col-md-12 mb-4">
          <a href="{% url 'pages:post_detail' pk=post.id %}" class="bo">
            <div class="card text-dark bg-light">

              <div class="row g-0">
                <div class="col-md-4" style="overflow: auto;">
                  {% if post.image %}
                    <div class="img_div" style="background-image: url('{{ post.image.url }}');"></div>
                  {% else %}
                    <div class="img_div"></div>
                  {% endif %}
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <h5 class="card-title ">{{ post.title }}</h5>
                    <p class="card-text">... </p>
                    <p class="card-text"><small class="text-muted">Last update: {{ post.updated_at }}</small></p>
                  </div>
                </div>
              </div>

            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </main>


{% endblock content %}